title: Greg's Blog
author: Greg Nosan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi everyone! My name is Greg and this is my blog. I hope to share any thoughts and experiences on this site to share with the world. 

# social links
twitter_username: gregn_jr # DO NOT include the @ character, or else the build will fail!
github_username:  gregn-jr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
